---
kind: pipeline
name: on commit

steps:
  - name: Check that version file has been updated
    image: curlimages/curl
    commands:
      - sh auto_create_tag.sh
    environment:
      GITHUB_API_KEY:
        from_secret: GITHUB_API_KEY
trigger:
  event:
  - push
  branch:
  - master

---
kind: pipeline
name: on tag
steps:
  - name: build docker image
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      username: andrchalov
      context: ./docker
      dockerfile: ./docker/Dockerfile
      password:
        from_secret: DOCKER_REGISTRY_TOKEN
      tags:
        - ${DRONE_TAG}
  - name: publish release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_API_KEY
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      message: >
        {{#success build.status}}
          `${DRONE_REPO}`: release *${DRONE_TAG}* successfully builded and pushed to docker hub [info]({{build.link}})
        {{else}}
          `${DRONE_REPO}`: failed to create release *${DRONE_TAG}* [info]({{build.link}})
        {{/success}}
      token:
        from_secret: TELEGRAM_TOKEN
      to:
        from_secret: TELEGRAM_CLIENT
      format: markdown
    when:
      status: [ success, failure ]
trigger:
  event:
  - tag
